server:
  port: 8082

spring:
  application:
    name: practitioner-service
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_office
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 