server:
  port: 8081

spring:
  application:
    name: patient-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
